def display_menu():
    print("===== 할 일 목록 관리 =====")
    print("0. 종료")
    print("1. 할 일 추가")
    print("2. 할 일 수정")
    print("3. 할 일 삭제")
    print("4. 할 일 목록 조회")
    print("5. 날짜별 할 일 목록 조회")
    print("6. 우선순위별 할 일 목록 조회")
    print("==========================")